### ISSUE TITLE
server hangs if a handler returns undefined

### ISSUE THREAD

**Issue by danielroe** [nuxt-contrib/h2#11]
with automatic promisifying, if a handler returns undefined, the promise never resolves and the server hangs...

Is there a reason we don't immediately `resolve(undefined)` if the handler does?

**Comment by pi0** [comment]
Nice catch, but something i'm afraid that, is we would continue to next middleware if handle uses an async operation like this:

```js
export default (req, res) {
  db.getUser((user) => {
     res.end(JSON.stringify(user))
  })
}
```

A legacy middleware like this would be broken.... I was supposing middleware (or better handle since has only two params) should always end request and so we listen to `res.end`. Do you have a case that it causes server to hang-up?

**Comment by danielroe** [comment]
Very good point....! Will remove from #10

**Comment by pi0** [comment]
I see... In that case we can introduce something like `{ legacy: true }` and use modern syntax by default. Wdyt?

**Comment by danielroe** [comment]
I would really like that, but do we lose the benefit of interop with express middleware where the user doesn't have control over each `use()` call? Could we create an entire App instance with `{ legacy: true }` and have that behaviour apply to every handler...?

**Comment by danielroe** [comment]
For a repro of hang:

1. Clone https://github.com/danielroe/jiti-h2-tests
2. `yarn && yarn dev`
3. `http http://localhost:3000/api/js/csr` - fails
3. `http http://localhost:3000/api/ts/csr` - succeeds (e.g. falls back to Nuxt 404)

**Comment by pi0** [comment]
Thanks for repro @danielroe! Actually it helped to find two issues:
- When using h2 as a sub-app, we should use `req.url` not `originalUrl` to allow using relative paths (no `/api/js` in middleware itself)
- Since connect detects `app.handle`, the hanging issue was happening so i made it hidden under `app._handle` ([src](https://github.com/senchalabs/connect/blob/52cf21b211272519caeef3bb5064c3430f4feb43/index.js#L87))
